# Generated by Django 3.0.4 on 2020-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.BooleanField()),
                ('breathing_difficulties', models.BooleanField()),
                ('throat_pain', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('corporal_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contact_risk_people', models.BooleanField()),
                ('other_info', models.CharField(max_length=300)),
            ],
        ),
    ]
