# Generated by Django 3.0.4 on 2020-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_auto_20200315_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='corporal_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='other_symptoms',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
