# Generated by Django 3.0.4 on 2020-03-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='questionary',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionary',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionary.PersonalInfo'),
            preserve_default=False,
        ),
    ]
